name: Notification on Schedule

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  notificate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Bundle Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Execute
      run: bundle exec ruby notificate-atcoder-date.rb
      env:
        SLACK_URL: ${{ secrets.SLACK_URL }}
