name: Regular Execution

on:
  schedule:
  - cron: "0,10,20,30,40,50 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3

    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --path vendor/bundle
        bundle exec ruby notificate-atcoder-date.rb
        # bundle install --jobs 4 --retry 3
        # bundle exec rake
      env:
        SLACK_URL: ${{ secrets.SLACK_URL }}
